internetarchive/wayback-machine-webextension

- index.html
- scripts/popup.js
User can now directly search any site on Wayback Machine's search
> Integrated Wayback Machine's site search

- index.html
- scripts/popup.js
After the merge there was a problem that there were multiple search bars.
This PR resolves it to a single search bar and i also have made minor user Interface changes so as to make eye-catching
> Rectified Merge - Single search bar

- index.html
- scripts/background.js
- scripts/popup.js
I have been working on the feature of showing the summary of a given site (Alexa Rank).
Here is the result.
**When the user is on a website and he clicks on the extension icon,he will get a small summary of the current webpage in the popup window**
> Added feature that provides a summary of a given site(Alexa Ranking)

- index.html
- scripts/background.js
- scripts/popup.js
This PR is towards integrating social sharing feature. Currently, it supports Facebook, Twitter, Linkedin and Google+ sharing but other social sites can easily be added in future. 
Below you can see this feature working:
@rchrd2  @markjohngraham  Kindly review this PR.
> Social Sharing Feature

- index.html
- manifest.json
- scripts/background.js
- scripts/popup.js
This version does NOT include automatic URL archival and visual feedback to the user based on the availability of the URL in the archives.
> One-click summary view of a given site (Alexa and Whois)

- index.html
- manifest.json
- scripts/background.js
- scripts/popup.js
This PR is towards adding the Context Menu entries for Wayback Machine Extension in Chrome Browser. The user can right-click on a web page to access the child entries save page now, recent version and first version under Wayback Machine Entry.
@rchrd2 @markjohngraham Kindly review this PR.
> Added Context Menu Entries For Wayback Machine

- index.html
- scripts/popup.js
This PR integrates the Wayback Machine's Site Search into the extension (showing suggestions).
Below you can see the working of this feature.
@rchrd2  @markjohngraham  Kindly review this PR.
> Added Wayback Machine Search Site inside extension with suggestion feature

- scripts/RTcontent.js
- scripts/popup.js
Remove redundant code and simplify. No new feature is added.
> Optimise js

- scripts/background.js
- scripts/popup.js
Remove unnecessary functions in `scripts/popup.js`. Make code much more
compact.
Trim whitespace in `scripts/background.js`.
> Further JS trim down

- css/sequences.css
Font style changed to bold using Font-weight property.
> Updated as on issue #103

- manifest.json
- scripts/background.js
- settings.html
Added archive.org URL for whois,twitter and small typo changes
@vbanos Please check this PR.
> Added archive.org URL for whois,twitter and small typo changes

- manifest.json
- scripts/alexa.js
- scripts/background.js
Added archive.org URL and fixed a bug in alexa Context
@vbanos Please check this PR
> Added archive.org URL and fixed a bug in alexa Context

- manifest.json
- scripts/background.js
I have started documenting the code. 
Please check it @vbanos . Any improvement suggestion is welcomed.
> Added documentation to the code

- settings.html
Fix typos. Make text more consistent. Remove redundant text.
> Improve settings page texts

- alexa.html
- annotation.html
- annotationURL.html
- css/alexa.css
- css/annotation.css
- css/common.css
- css/recommendations.css
- css/similarweb.css
- css/singleWindow.css
- index.html
- manifest.json
- recommendations.html
- scripts/background.js
- scripts/popup.js
- scripts/recommendations.js
- scripts/settings.js
- settings.html
- similarweb.html
- singleWindow.html
- tagcloud.html
This is a context feature which shows Web News->Tv news. 
@vbanos Please check it . It can be tested on the URL like https://www.huffingtonpost.com/entry/alex-jones-infowars-app-apple-google_us_5b694ec3e4b0de86f4a4bc1d and user can see a button on the Pop-up window of extension
> Added Feature to show Web News->Tv news

- scripts/recommendations.js
Fixed bug regarding Tv news Context feature !!
@vbanos kindly review it .
> Fixed Tv news bug

- scripts/popup.js
- scripts/recommendations.js
This PR includes : 
1. Fixing bug where this feature was not working on some special websites
2. Handling event if we could not make any tv-news recommendation.
> Tv-news Feature bug Fix

- css/domaintools.css
- domaintools.html
- manifest.json
- scripts/background.js
- scripts/domaintools.js
- scripts/settings.js
- settings.html
@vbanos Please review this.
1. I have added domaintools context screen and replaced it by whois context screen!!
I have added domaintools html, JS and CSS files and made the necessary changes in the background.js file to support this context Screen. 
New settings have been added in settings.html and settings.js file. 
2. In this PR I have also set "show-all" context screen (by default) in the settings so that when the user load first time this extension and click on the "Show me context option", they will be shown all context screens.
Thank you!!
> Added Domaintools Context Screen

- css/booklist.css
- css/donatebook.css
- css/recommendations.css
- donatebook.html
- scripts/booklist.js
- scripts/donatebook.js
- scripts/popup.js
Also made some minor tweaks to tvnews CS
> Added generic donation page

- css/twitter.css
- scripts/background.js
- scripts/twitter.js
- twitter.html
@vbanos I have made modification on Twitter Context Screen looks. Changes are added in this PR.
> Added Modified twitter context

- manifest.json
- scripts/background.js
- scripts/settings.js
- settings.html
@vbanos I have added by-default all settings to off. User has to turn on each feature to see the results.
Thank you!!
> Added bydefault all settings to off

- css/common.css
- css/doi.css
- css/recommendations.css
- doi.html
- index.html
- manifest.json
- overview.html
- recommendations.html
- scripts/background.js
- scripts/booklist.js
- scripts/doi.js
- scripts/popup.js
- scripts/recommendations.js
- settings.html
Made several UI changes, especially in the DOI CS.  The next step is to make the settings window and popup window more consistent.
> Improved UI for TVNews and DOI

- css/booklist.css
- css/doi.css
- css/recommendations.css
- index.html
- recommendations.html
- scripts/booklist.js
- settings.html
tvnews spinner now spins.
"No ISNBs found" properly displays on wikibooks.
Amazon books CS text now references "Steal this book", as per Mark's request
> Fixed 2 bugs and made some UI changes

- css/booklist.css
- scripts/booklist.js
Some code is repetitive. This should be changed after tomorrow's demo.
> images and buttons now always align in wikibooks. 

- manifest.json
- scripts/background.js
@vbanos I have only fixed the bug in this PR.
Window CS was not auto-updating while the user is turning on that feature!!
> Fixed bug while auto-updating windows CS

- scripts/popup.js
This required that I slightly change the way the news hosts are identified.
> added some news sources to list for tvnews

- doi.html
- package-lock.json
- package.json
- scripts/doi.js
- scripts/doi_loader.js
Write more compact and readable code using jQuery.
Use `eslint` to improve code readability in `scripts/doi.js`.
The logic and functionality remains exactly the same.
> Rewrite papers context UI using jQuery

- css/booklist.css
In the future, I'd like to implement the whole layout using flexboxes to be consistent. However, Mark wanted the layout cleaned up by saturday.
> Aligned images and buttons on wikibooks using flexbox.

- package.json
- scripts/doi.js
Source can be either archive.org or unpaywall.org
Bump version to 3.1.1
> Add "source" in papers context

- overview.html
- package-lock.json
- package.json
- scripts/overview.js
- scripts/overview_loader.js
- test/overview.spec.js
@vbanos I refactored overview.js using jQuery and added one test. There are other tests to be added for different functions. The error I mentioned of is now fixed. The test is running without any issue.
> Overview refactor

- scripts/background.js
I have added alexa-url and hoaxy_url in the global scope inside the context feature
> Added alexa-url and hoaxy_url in the global scope

- index.html
- scripts/popup.js
Some time ago, we had Alexa and whois buttons in the extension UI.
We have removed them but we didn't remove the code.
Also remove some unused commented-out code in `scripts/popup.js`.
> Removed unused old alexa and whois button code

- index.html
- scripts/amazon.js
- scripts/popup.js
- `borrow_books()` now calls api from a separate file, `scripts/amazon.js`
- The api request uses fetch and returns a promise
- `borrow_books()` uses JQuery
> The Amazon Books CS now uses the newer API

- css/doi.css
- scripts/booklist.js
- scripts/doi.js
- Uses flexboxes in doi.css so now the author's name always appears
- The anchor tags are now button elements.  This prevents a bug when the user right-clicks the button and clicks "open in new tab"
> Minor UI changes to wikipedia books and papers

- scripts/booklist.js
- scripts/wikipedia.js
- test/wikipedia.spec.js
Also adds some padding to the citation button.
> Improves ISBN search function for wikipedia.js

- css/recommendations.css
- recommendations.html
- scripts/recommendations.js
- scripts/recommendations_loader.js
- test/recommendations.spec.js
Uses Jquery for DOM manipulation.  
2 things:
- Now when you hover over the tvnews clip, the cursor doesn't change to a finger
- from a UI perspective, it's hard to tell that the image is clickable.  
- before, the img was in an anchor tag, but the right-click options showed up for the anchor tag
- I broke up the program into more functions, but I am not really sure what to test.  
- The script just fetches JSON and does DOM manipulation.  
- I'd love to hear any ideas for tests.
> Refactor for recommendations.js (TV news CS)

- scripts/settings.js
- settings.html
- The logic behind `validate()` seemed a little wonky, but it works, so I didn't touch it. 
- I think it would make more sense instead of having a `select all` checkbox, to have a button instead.
- Possibly make a `clear all` button and a `toggle all` button
- I also was thinking of calling `save_options()` on window close instead of requiring the user clicks the `save` button
> JQuerifies settings.js

- css/settings.css
- scripts/settings.js
- settings.html
- Every setting should just be title and checkbox (or dropdown selector).
- Window closes on save.
> Minor UI Changes for Settings window

- README.md
extension link added to the readme.
Fixes internetarchive#232.
@vbanos please review.
> extension link added to readme

- css/index.css
- index.html
Simplify HTML greatly and remove redundant CSS rules as well.
> Remove HTML Tables from index.html

- domaintools.html
- scripts/domaintools.js
- scripts/domaintools_loader.js
- test/domaintools.spec.js
- test/setup.js
@vbanos I have refactored domaintools.js and added unit tests for it. Let me know if any changes have to be made. Thank you
> Domaintools refactor

- package-lock.json
- scripts/background.js
@vbanos I refactored background.js such that chrome.storage.sync.get is not called multiple times. I also solved the problem Max described ( asynchronous nature of chrome tabs/windows opening). Please review this PR
> Refactored chrome.storage.sync.get calls in background

- scripts/background.js
- scripts/popup.js
Please try it out to identify any badge bugs.  
I notice on amazon, if you run Save page now, it doesn't replace the icon with a check.  But I tested this behavior previously and it didn't do it then either.
> Auto-archive now doesn't overwrite the icon badge, it appends to it.

- index.html
- manifest.json
- scripts/background.js
- scripts/popup.js
@vbanos I edited background.js for compatibility with Firefox. Some bugs remain
1. If contexts are shown in tabs , the first context does not update if a new web page is opened.
2. Find cited books/papers doesn't work if single window chosen
3. 'Show me context' cannot be clicked on a new page if existing contexts are open for both tabs and windows . The new tabs , windows which open re-render infinitely.
None of the changes I made break any functionality for Chrome. I will be fixing the above mentioned bugs.
> Edited for firefox compatibility

- css/index.css
- index.html
@vbanos I have addressed the issue regarding the Feedback Button CSS.
Thank you!!
> Feedback button css issue solved

- css/index.css
- images/baseline-feedback-24px.svg
- index.html
- package-lock.json
- package.json
- scripts/popup.js
@vbanos This PR contains the suggested changes by @mekarpeles for the new UI of the extension. This will look much like this 
Please review it. Thank you!!
> Suggested new UI

- scripts/overview.js
- singleWindow.html
Total overhaul the captures overview section in the single window mode.
Present the same information in a better way.
Remove redundant text.
> Single Window Context captures overview

- css/singleWindow.css
- scripts/overview.js
- scripts/singleWindow.js
- singleWindow.html
Remove redundant HTML and CSS.
Use bootstrap CSS properly.
Fix bug with Last capture link.
> Single page context markup / js / css cleanup

- overview.html
Total overhaul of the overview context. The previous page had a lot of
grammar / syntax errors. Now its more concise and easy to read.
> Improve Wayback Machine Overview context layout

- scripts/wikipedia.js
- test/annotation.spec.js
- test/booklist.spec.js
- test/recommendations.spec.js
@vbanos This PR fixes the problem for which the unit tests were failing as @MaxReinisch had described. Please review it .
> Exported getMetadata function, inluded Jquery in annotation.spec.js

- scripts/background.js
- scripts/utils.js
- test/utils.spec.js
- moved all url validation functions into utils.js
- named the one that checks a blacklist isNotExcludedUrl and it takes in a url and a blacklist (was isValidUrl)
- named the one that checks that url is string and with proper protocol isValidUrl (instead of isValidSnapshotUrl)
- added unit tests
As for ways to actually change the functionality, I was thinking of making the blacklist a set instead of an array.
> Addresses URL validation

- test/booklist.spec.js
Fixed failing of testing of getMetadata in booklist.specs.js 
@vbanos This the fix to the error I have mentioned earlier about failing.
> Removed extra testing of getMetadata

- css/index.css
Setting the value of min-width and max-width to same value has the same effect as setting the width directly.
> (update) Reduce Redundant CSS to Single Line in index.css

- scripts/tagcloud.js
- scripts/tagcloud_loader.js
- tagcloud.html
- test/tagcloud.spec.js
@vbanos I have tried to add testing to tagcloud.js in this PR.
> Added testing to tagcloud.js

- scripts/amazon.js
- scripts/background.js
- scripts/popup.js
Reverts internetarchive/wayback-machine-chrome#319
> Revert "fixing issue/314" due to bug

- index.html
@vbanos @MaxReinisch  I have added title to last row icons of the UI.
> Added title to last row icons of the UI

- css/doi.css
Fixed UI bug in find cited papers.
> Fixed #316

- scripts/singleWindow.js
- scripts/tagcloud.js
Removed the function findWeightOf() as it is no longer needed now. Now the complexity has reduced from O(n x m) to O(m).
> Optimized tag's weight find concept and fix tag-cloud issue in single page view

- scripts/popup.js
@MaxReinisch I have removed some used variables from popup.js.
> Removed unused variables from popup.js

- index.html
- scripts/popup.js
> Fixed #304

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> Added bug report, feature request issue templates

- .eslintrc
- css/index.css
- index.html
- scripts/booklist.js
- scripts/citations.js
- scripts/popup.js
- settings.html
Reverts internetarchive/wayback-machine-chrome#361
> Revert "Context options refurbish"

- scripts/RTcontent.js
@MaxReinisch I have removed unused variable from RTcontent.js
> Removed unused variable from RTcontent.js

- index.html
Added the main Site hyperlink to the logo.
> Internet Archive Logo: Hyperlinked,Hoverd.

- css/index.css
- scripts/popup.js
In this PR, I have fixed the issue with search box. Now you can hit enter to go to the search result and arrow keys are supported for suggestion list navigation.
> fixed searchBox feature

- scripts/amazon.js
- scripts/background.js
- scripts/popup.js
- scripts/settings.js
- scripts/wikipedia_loader.js
- settings.html
In this PR, I have added the 'R' label standing for Resource: 
- Amazon Books
- Wikipedia Books
- Wikipedia Cited papers
- TV News
And now all of these features will be toggled by on checkbox.
> Create Resource label 'R'

- package-lock.json
- scripts/background.js
- scripts/recommendations.js
- scripts/recommendations_loader.js
Forgot to add in commit message, final threshold is .85
> Adds Similarity threshold to TV news

- index.html
- scripts/popup.js
- scripts/settings.js
In this PR, I did:
1. Fixed tooltip not disappearing problem
2. Now tab/window radio button can be toggled by clicking the outer box as well
3. The back button won't be highlighted
> SettingUI bug fix and functionality improvement

- scripts/background.js
- scripts/booklist.js
Previously in [this case](https://en.wikipedia.org/wiki/Probability_mass_function), it would just display error message "error"
> fixed error handling in booklist.js

- scripts/background.js
- scripts/popup.js
- scripts/utils.js
3 things: 
1. Testing auto_save on reddit.com/new threads, I notice that text posts follow good behaviour but other posts make a bunch of availability requests and save requests.  
2. I want to add validation for the `save now` button, but I was having some issues with the status check returning errors because the URL was invalid, but I make the request with the job_id and I don't even touch the url.  I think this is a backend issue. 
3. When we open a tab/window with the saved url's snapshot after clicking `save now`, it reloads a couple of times and then redirects to an invalid url.  This has been tested manually with the extension disabled, so I believe it is a backend issue.  Tested with https://web.archive.org/save/https://www.reddit.com/r/learnprogramming/comments/d5mlgj/is_it_possib …
> Updates Save Page Now features

- scripts/background.js
- scripts/popup.js
- scripts/utils.js
This PR Improves the UI for features using spn2:
- Improves error handling and user action feedback
- Makes Last Saved feature consistent with saves from spn2
- Prompts user login to use features. 
Concerns:
- Needs to find a place to explain that logging in is required. 
- Can put message in Save Now button 
- Not sure where to do this for auto_save
> Improves UI and prompts login on spn2

- context.html
- scripts/overview.js
- scripts/tagcloud.js
This PR includes fixes of two things
1. Handle API failure in tag cloud and overview context
2. Show appropriate message in the UI
> Handle API failure and show appropriate message in tagcloud and overview context

- context.html
- css/context.css
- scripts/annotation.js
- scripts/context.js
- scripts/overview.js
I have added the new/updated context screen UI in this PR.
Moreover I handled the API failure message in the wayback overview context
> New ui of context screen and handled api error in overview context screen

- scripts/background.js
In this PR, I have added validation of URLs when the user is  proceeding through context menus actions
> Validation of URLs when proceeding through context menu actions

- .eslintrc
- .eslintrc.json
- STYLE_GUIDE.md
- scripts/popup.js
Please take a look and let me know what you think.
> Created a new Style Guide

- .eslintrc
- .eslintrc.json
- STYLE_GUIDE.md
- index.html
- scripts/background.js
- scripts/popup.js
- scripts/settings.js
- Implemented Outlinks & Screenshot options for Save Page Now
- Added Settings option for sending Outlinks email
> Implement Save Page options

- css/context.css
- scripts/background.js
1. Fix bug of auto_update context screen url empty
2. Add Dark Mode to Context Screen
> Fix bug of auto_update context screen url empty and Add Dark Mode 

- scripts/popup.js
1. Change url search as per search in wayback machine https://web.archive.org/
> Change URL search validation as per search in wayback machine

- css/index.css
- index.html
- recommendations.html
- scripts/recommendations.js
1. Enabled the working model of Related Archives Resources
2. Fix bug of showing loader all the time
> Working model of related archived resources

- scripts/utils.js
In this PR I have added some URLs to the excluded_urls list specified to firefox
> Add excluded urls specified for firefox

- README.md
In this PR, I have added Firefox installation process in README.md while developing
> Add firefox installation process in README.md

- scripts/settings.js
Fixed the error in Show All Contexts checkbox.
> Fixed Show All Contexts

- README.md
- STYLE_GUIDE.md
- scripts/alexa.js
- scripts/annotation.js
- scripts/archive.js
- scripts/background.js
- scripts/booklist.js
- scripts/booklist_loader.js
- scripts/context.js
- scripts/doi.js
- scripts/doi_loader.js
- scripts/domaintools.js
- scripts/overview.js
- scripts/popup.js
- scripts/recommendations.js
- scripts/recommendations_loader.js
- scripts/settings.js
- scripts/tagcloud.js
- scripts/tagcloud_loader.js
- scripts/utils.js
- scripts/welcome.js
- scripts/wikipedia.js
- scripts/wikipedia_loader.js
Fixing some issues reported by eslint. Also tweaked README.
> Added 'global' comments to remove eslint 'no-undef' errors + minor bug fixes

- test/annotation.spec.js
- test/doi.spec.js
- test/domaintools.spec.js
- test/overview.spec.js
- test/recommendations.spec.js
- test/setup.js
- test/utils.spec.js
In this PR I have added 
1. Add test cases for new excluded urls
2. Format all .spec.js file using eslint
> Add test cases for new excluded urls, format all .spec.js file as per eslint

- context.html
- css/context.css
In this PR, I have updated the annotation context screen UI. I have also removed some custom css which are not in use now.
Thank you !
> Update the annotations context screen

- scripts/alexa.js
- scripts/annotation.js
- scripts/archive.js
- scripts/background.js
- scripts/booklist.js
- scripts/context.js
- scripts/doi.js
- scripts/domaintools.js
- scripts/index.js
- scripts/overview.js
- scripts/popup.js
- scripts/recommendations.js
- scripts/settings.js
- scripts/utils.js
In this PR I have formatted all scripts file as per eslint and also removed some unused vars in the code.
> Formatted all scripts file as per eslint and removed some unused vars

- css/index.css
- css/settings.css
- index.html
This is a suggested improvement for the switch UI in Settings menu as mentioned in #488 .
> Improve the switch UI in Settings menu

- manifest.json
- scripts/background.js
- scripts/recommendations.js
- scripts/utils.js
- scripts/welcome.js
In this PR
1. I have added a feature so that the chrome extension storage is being reset ,every time you reload/install the extension. (This was a issue in firefox)
2. Remove warning details in firefox and remove chrome.system.dislay api used. Also removed from "system.display" from permissions in manifest.json
> Firefox extension fix

- css/settings.css
- index.html
This PR improves the indentation of the tooltip buttons (? buttons) and the second line of text in Settings menu.
> Improved indentation in Settings menu

- css/welcome.css
The following changes have been made:
1. Welcome Page is now responsive.
2. The content is now aligned as JUSTIFIED.
> Welcome Page Responsive

- scripts/background.js
- scripts/popup.js
- scripts/settings.js
- scripts/utils.js
Fixes all the issues listed in #493.
> Wayback Count issues

- context.html
- css/common.css
- css/context.css
- css/domaintools.css
- css/index.css
- css/settings.css
- index.html
- Made UI improvements to the Settings switch UI, including for dark mode.
- Settings indentation tweaks.
- Styles and Dark Mode tweaks for context screens.
> Dark Mode and CSS tweaks

- context.html
- css/context.css
Contexts Page is more responsive now.
> Improve Responsiveness of Contexts Page

- context.html
- css/context.css
- index.html
In this PR, I have removed Tag-cloud and DomainTools context for next release
> Remove tagcloud and domaintools temporarily

- css/context.css
This PR slightly improves the look of the scrollbar in the Contexts Page.
> Modfied Scrollbar in Contexts Page

- css/settings.css
- scripts/background.js
- scripts/utils.js
- test/utils.spec.js
This also localizes the date or time string shown when hovering over the Save Page Now button.
> Show time when Save Page is within last 24 hours

- scripts/background.js
- Save Page Now button works again.
- Auto-save works.
- Toolbar icon changes to red 'S' during save, then a checkmark when finished saving.
> Bug fix for SPN and auto-save

- css/index.css
- index.html
- scripts/popup.js
In this PR, I have added a message "URL not supported" that will be shown above the input-box (stating that most the features of our extension will not work) when the URL is part of excluded URLs.
Fixes #510
> Show message when URL is in the list of excluded urls

- context.html
- css/context.css
- index.html
- scripts/tagcloud.js
@cgorringe I have enabled again "Tagcloud" feature in the context. Thank you !
> Enabled tagcloud feature after the API fix

- context.html
- css/context.css
- scripts/tagcloud.js
Just did some CSS tweaks to change background color, add a rounded border, etc.
> Tweaked styles for Tag Cloud context page

- scripts/background.js
- scripts/doi.js
- scripts/domaintools.js
- scripts/overview.js
- scripts/popup.js
- scripts/tagcloud.js
- scripts/utils.js
In this PR , I have changed the host url by checking the browser. This is still under development.
> WIP: Change host URL by checking the browser

- scripts/background.js
Fixed some issues when the 'S' toolbar icon gets displayed.
> Improved Save Status

- context.html
- css/context.css
- scripts/context.js
- scripts/tagcloud.js
NO loader was showing up when the API call was taking some time. I have fixed that
> Fix loader bug in tagcloud context screen

- index.html
- scripts/background.js
- scripts/settings.js
- scripts/utils.js
In this PR I have added 'Enable 404 popup' in "General Settings". By default it is "checked" , the users can turn off as per their needs.
Fixes #506 
Here's a 404 link to test against:
http://purl.oclc.org/docs/inet96.html
> Add 'Enable 404 popup' in settings as a option

- scripts/background.js
- scripts/context.js
- scripts/utils.js
> Reopen same context tab on reload

- scripts/background.js
In this PR i have changed the type of variable `newshosts` from list to set, so that the lookup time in `newshosts` will take constant time.
Fixes #520
> Change newshosts from list to set to make lookup time constant

- context.html
- scripts/alexa.js
- scripts/background.js
- scripts/popup.js
In this PR I have removed some used code from our codebase. Also I have fixed "loader not removing" issue in the alexa context
> Code refactor

- manifest.json
- scripts/utils.js
- test/utils.spec.js
In this PR I have added some extra urls based on firefox browser!
> Added extra urls to excluded list based on firefox browser

- css/archive.css
In this PR I have increased the z-index of the 404-popup!
> Increase z-index in archive popup

- scripts/utils.js
- test/utils.spec.js
> Added URLs to excluded_urls list

- context.html
- css/context.css
- scripts/context.js
This PR enables auto adjustment of the tab width in 'Context' screen navbar.
> Auto adjust tab width

- scripts/background.js
- scripts/popup.js
- scripts/settings.js
- scripts/utils.js
> Wayback count badge fix

- scripts/background.js
> Fix right click context menu save not working

- scripts/background.js
- scripts/popup.js
Don't Clean URL while saving and fetching last save.
> Don't save pages on 'web.archive.org'

- scripts/background.js
- scripts/utils.js
> Show notification instead of alert in firefox

- scripts/background.js
- scripts/popup.js
In this PR I have handled error while doing SPN and showing proper message for that in the UI.
Thank you !
> Handle error and show proper message if error happens while doing SPN

- scripts/context.js
- scripts/utils.js
In this PR I have optimised the code in popup.js
> Optimise context.js

- scripts/popup.js
This PR removes some code which is no longer needed.
> Remove code that is not needed

- scripts/overview.js
- scripts/tagcloud.js
In this PR I have handled many edge cases during API calls in overview context
> Handle error in overview and tagcloud context

- scripts/wikipedia.js
This is a small improvement over wikipedia feature so that it will open a new tab on every click
> Open the reference link in a new tab

- scripts/settings.js
> Update settings tooltip text

- index.html
- scripts/background.js
- scripts/settings.js
- scripts/utils.js
- scripts/welcome.js
- welcome.html
Some code tweaks:
- Prevents "Outlinks" and "Screenshot" checkbox text from being highlighted.
- Removes duplicated code that initializes settings.
- Agreement page now only displays on first install and not updates.
- Updates the settings defaults to mostly True on install.
- Rearranges General Settings.
> Misc Tweaks 1

- README.md
- contribution-guide.md
- package-lock.json
@cgorringe Please review the PR
> Solve Issue #531 : Added a contribution Guide

- scripts/alexa.js
- scripts/annotation.js
- scripts/archive.js
- scripts/background.js
- scripts/booklist.js
- scripts/booklist_loader.js
- scripts/context.js
- scripts/doi.js
- scripts/domaintools.js
- scripts/overview.js
- scripts/popup.js
- scripts/recommendations.js
- scripts/settings.js
- scripts/tagcloud.js
- scripts/tagcloud_loader.js
- scripts/utils.js
- scripts/welcome.js
- scripts/wikipedia.js
- scripts/wikipedia_loader.js
This PR changes the storage type from `chrome.storage.sync` to `chrome.storage.local` and upgrades the anonymous functions to arrow functions format.
> Change storage to local and Use arrow functions

- css/booklist.css
- css/doi.css
- css/donatebook.css
`.rec_results` class was redundant So I have removed the class
> Removed redundant CSS

- webextension/css/context.css
- webextension/scripts/alexa.js
In this PR I have fixed alexa context screen loading issue. Also in the overview context, the thumbnail is centre aligned in overview context !
> Fix alexa and overview context screen bug

- webextension/scripts/background.js
- Fixes missing Error message and prevents call to status when SPN returns an error.
- Fixes missing domain prefix on save/status call.
> Adds a notification when SPN returns error

- webextension/about.html
- webextension/booklist.html
- webextension/css/about.css
- webextension/css/booklist.css
- webextension/css/context.css
- webextension/css/doi.css
- webextension/css/recommendations.css
- webextension/doi.html
- webextension/recommendations.html
- webextension/scripts/doi.js
- webextension/scripts/recommendations.js
This PR makes style adjustments to some pages and rewrites the code according to the `STYLE_GUIDE.md`
> Adjust styles

- webextension/css/index.css
- webextension/css/settings.css
- webextension/index.html
Solves an item for UI/UX Improvements #600
- Groups the Save Page options by drawing a frame to show them related to SPN button.
- Added the 'R' and 'S' icons to Settings items to show how they're linked.
> Frame around SPN options

- webextension/scripts/popup.js
In this PR I have removed "URL Not Supported" text if the user is typing anything in the search input box !
> Change "url-not-supported" text based on search box input

- README.md
- test/utils.spec.js
- webextension/scripts/utils.js
- Added excluded URLs for edge.
- Updated README.md.
> Updates to support in Microsoft Edge

- webextension/context.html
- webextension/css/context.css
- webextension/scripts/context.js
In this PR, I have added URL name to be shown in every context screen
> Add url in every context screen

- test/overview.spec.js
- webextension/context.html
- webextension/scripts/overview.js
In this PR I have improved the overview context
> Use utils function to get the overview count

- webextension/scripts/background.js
> Retry /status after 6000ms

- webextension/css/doi.css
- webextension/scripts/doi.js
In this PR, I have updated the doi api and made some css fix in cited paper context.
> Update doi api and css fix in Cited Paper context

- webextension/scripts/background.js
This PR resolves the issue #610
> Context menu to work on the link URL 

- test/utils.spec.js
- webextension/scripts/popup.js
In this PR, I have applied debouncing concept to the input-box to reduce the network call while searching.
> Introduced debouncing concept

- webextension/scripts/background.js
In this pr I have double checked `tabs` and `tabs[0]` exist or not !
> Removes error "id of undefined" from background.js

- webextension/scripts/about.js
- webextension/scripts/popup.js
- webextension/scripts/utils.js
This PR adds API for Microsoft Edge Browser.
> Add API for Edge

- webextension/css/index.css
- webextension/index.html
- webextension/scripts/background.js
- webextension/scripts/popup.js
This PR adds an animation to the background of SPN button, giving a more interactive experience to the user.
> Animate SPN

- webextension/css/context.css
- webextension/css/settings.css
- webextension/index.html
- webextension/scripts/settings.js
- webextension/scripts/utils.js
Move 'Auto-Update Contexts' to 'Context' menu to reduce the height of 'General' settings menu.
> Move 'Auto-Update Contexts' to 'Context' menu

- webextension/scripts/background.js
> Fix 404 firefox issue

- webextension/index.html
> adjusting back button margins

- webextension/scripts/popup.js
This PR lightens/darkens the SPN button based on user's Log in status.
> Dim SPN button

- webextension/css/index.css
- webextension/index.html
- webextension/scripts/popup.js
- webextension/scripts/settings.js
- webextension/tagcloud.html
Modified the UI after team meeting. Buttons now have variable widths to better display text, and some refactoring.
> Updated Redo of the UI

- webextension/scripts/background.js
This PR handles error for TV News Clips when JSON format is invalid.
> Handle error for TV News Clips

- webextension/bulk-save.html
- webextension/css/bulk-save.css
This PR tweaks Bulk Save CSS and removes unused code.
> Tweak "Bulk Save" CSS

- webextension/css/common.css
- webextension/css/index.css
- webextension/css/settings.css
- webextension/index.html
- webextension/manifest.json
- webextension/scripts/background.js
- webextension/scripts/login.js
- webextension/scripts/popup.js
- webextension/scripts/settings.js
Some improvements include:
- rearranging buttons
- widening popup
- cleaning up & refactoring CSS & HTML
- renaming CSS IDs and updating JS
- moving inline styles to css files
> HTML/CSS Refactoring

- webextension/scripts/background.js
- webextension/scripts/popup.js
- webextension/scripts/utils.js
This PR removes focus from the newly opened window(s) and prevents the removal of the toolbar icon.
> Open window without removing toolbar icon

- webextension/manifest.json
- webextension/scripts/background.js
- webextension/scripts/overview.js
- webextension/scripts/popup.js
- webextension/scripts/settings.js
- webextension/scripts/utils.js
Implements #475 by adding datetime tooltips to the Oldest and Newest buttons.
Works only when Wayback Count is turned on.
> Adds datetime tooltips to Oldest and Newest buttons

- test/tagcloud.spec.js
- test/utils.spec.js
- webextension/scripts/annotation.js
- webextension/scripts/bulk-save.js
- webextension/scripts/settings.js
- webextension/scripts/tagcloud.js
- webextension/scripts/utils.js
Get tests running again and passing, and added a new test.
> Unit Test Fixes 2

- package-lock.json
- package.json
- webextension/css/index.css
- webextension/index.html
- webextension/scripts/popup.js
Fixes #453
I have added the copy 'share-link' icon with the other social media share icons and a message when the link is copied.
Please refer to the following screenshots and suggest changes if any!
> Added Copy share link icon and functionality to display "link copied" message

- webextension/scripts/background.js
- webextension/scripts/popup.js
> Reduce available api calls frequency and use cached value

- webextension/scripts/background.js
This PR is an improvement to #692 to introduce more caching
> More caching even if wayback count option is not checked

- CONTRIBUTING.md
The repository name and folder name had to be updated.
> Have updated CONTRIBUTING.md

- README.md
> Tweaking browser icons in README

- webextension/scripts/bulk-save.js
Added a new feature which will show a error message while doing a bulk save->import all bookmarks if the browser doesn't contain any bookmarks
> Added New feature to show error message while doing bulk save

- webextension/scripts/bulk-save.js
> Show login error when the error is only with login in Bulk Save

- webextension/bulk-save.html
- webextension/css/bulk-save.css
- webextension/scripts/bulk-save.js
This is issue number #691. Added Outlink and Screenshot option to Bulksave
> Added Outlink and Screenshot option to Bulksave

- TESTING_GUIDE.md
- webextension/css/archive.css
- webextension/dnserror.html
- webextension/scripts/archive.js
- webextension/scripts/background.js
- webextension/scripts/dnserror.js
> Created a custom page to show DNS failure checks and redirect to offer archived URL

- webextension/scripts/background.js
- webextension/scripts/fact-check.js
I have removed the message "Cannot reach the server at the moment !" as the `error` object in the response means no fact checks found for a given URL.
> Change the title when no fact checks available for an URL

- TESTING_GUIDE.md
- webextension/scripts/alexa.js
- webextension/scripts/annotation.js
- webextension/scripts/background.js
- webextension/scripts/bulk-save.js
- webextension/scripts/context.js
- webextension/scripts/domaintools.js
- webextension/scripts/fact-check.js
- webextension/scripts/overview.js
- webextension/scripts/tagcloud.js
> Bulk Save fix to import bookmarks containing encoded URLs

- TESTING_GUIDE.md
- webextension/scripts/background.js
- webextension/scripts/popup.js
- webextension/scripts/utils.js
Fix for #279, updates Social Share buttons, and better handling of URL encoding issues.
> More encoded URL fixes and updated Social Share links

- test/setup.js
- webextension/scripts/annotation.js
- webextension/scripts/tagcloud.js
- webextension/scripts/utils.js
This PR is a fix to the issue #736
> Added a variable to check the testing environment

- webextension/scripts/background.js
> Fix false 404 popup

- webextension/scripts/background.js
- webextension/scripts/bulk-save.js
Hopefully fixes the miscount of Saved URLs reported in #755, and some other potential edge cases discovered.
All this still needs to be tested...
> Bug fixes to Bulk Save

- webextension/css/bulk-save.css
- webextension/manifest.json
- webextension/scripts/bulk-save.js
In Bulk Save, URLs with a Green status get converted to links that point to the archived version on the Wayback Machine. #743
> Converts Bulk Saved URLs into Wayback links when done

- webextension/bulk-save.html
- webextension/css/bulk-save.css
- webextension/scripts/bulk-save.js
Added a legend to explain symbols in Bulk Save. #757
> Bulk Save Legend

- webextension/bulk-save.html
- webextension/css/bulk-save.css
- webextension/scripts/bulk-save.js
Added save option to Bulk Save to only save URLs that have not been archived within a given number of days. 
Closes #746
> Bulk Save option to archive URLs only within given days

- webextension/css/bulk-save.css
- webextension/scripts/bulk-save.js
> disappearing add container fix in Bulk Save

- webextension/scripts/background.js
> Fix "Show Resources During Save" window if any URL is recently archived

- webextension/index.html
> Swap General and Context setting tabs

- package.json
- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/about.html
- webextension/index.html
- webextension/manifest.json
- webextension/scripts/background.js
- webextension/scripts/bulk-save.js
- webextension/scripts/overview.js
- webextension/scripts/popup.js
- webextension/scripts/settings.js
- webextension/wbmsummary.html
Also tweaked a label in the Bulk Save window due to user feedback.
> Remove Bulk Save and rearrange other popup buttons

- package.json
- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/css/index.css
- webextension/index.html
- webextension/manifest.json
- webextension/scripts/background.js
- webextension/scripts/popup.js
- webextension/scripts/settings.js
- webextension/scripts/utils.js
- Removes flipping SPN button after login.
- Adds Last Saved label.
- Swap Settings tab default.
- Add URL count to "Archiving..."
- Ensure SPN button can't be clicked again while archiving.
- Fixes some #795 
v2.999.12
> UI tweaks to SPN button

- webextension/scripts/popup.js
> Check if the url is invalid before searching for tweets

- package.json
- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
- webextension/scripts/popup.js
fixes #816 by disabling search box (and checkboxes) and also #815 which appears to no longer occur (or else wasn't able to duplicate it) on Safari.
> Fix for SPN button remaining in Archiving state

- package.json
- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
- webextension/scripts/background.js
- webextension/scripts/popup.js
> Skip Availability check for Wayback buttons

- webextension/welcome.html
Privacy Policy updated in Welcome page for #848
> Updated Privacy Policy

- package.json
- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
- webextension/scripts/background.js
2 bug fixes:
- "Exclude URLs" window not showing in Safari.
- A race condition bug causing 404 popup to not display.
> Bug fixes for RC1

- webextension/scripts/archive.js
- webextension/scripts/background.js
- webextension/scripts/popup.js
- webextension/scripts/utils.js
> Fix error msg and links in multi-tabs

- package.json
- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
- webextension/scripts/tvnews.js
needed to revert and redo PR #865
> Remove threshold value comparision in tvnews.js (redo)

- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
- webextension/scripts/background.js
fixes #863 
Tested on Chrome, Firefox, & Safari
> Increase WM count right after save success

- appstores/edge/README.md
- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/about.html
- webextension/manifest.json
- webextension/scripts/utils.js
Edge store links added to About page and feedback button.
> Add Edge store links

- webextension/scripts/background.js
- webextension/scripts/tvnews.js
Fixed 2nd and 3rd point from #873 .
Also fixed the speed issue while showing tvnews button in the ui
> Show tvnews button when the url loading is in progress and show href links on hover

- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
- webextension/scripts/background.js
fixes #877 
Tested in Safari, Chrome, and Firefox.
> Fix for false 'Server Not Found' errors

- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
- webextension/scripts/popup.js
> Fix Site Map button while in Word Cloud window

- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
- webextension/scripts/background.js
- webextension/scripts/utils.js
Making improvements to API calls.
> API improvements

- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
- webextension/scripts/utils.js
> Fix for simultaneous 404 error and context notice

- webextension/scripts/background.js
- webextension/scripts/utils.js
- webextension/scripts/welcome.js
> Fix for settings reset and welcome redisplay on upgrade

- webextension/scripts/background.js
- webextension/scripts/utils.js
> Only show right click menu when the user accept privacy and policy

- webextension/index.html
- webextension/scripts/popup.js
> Fix missing 'URL not supported' on Safari

- webextension/index.html
- webextension/scripts/popup.js
> Update activeURL to current after search box cleared

- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
- webextension/scripts/background.js
- webextension/scripts/popup.js
- webextension/scripts/utils.js
Says "Wayback Machine Unavailable" when sparkline API fails to indicate APIs unreachable, such as during a power outage.
> Status message when servers unavailable

- webextension/about.html
- webextension/css/about.css
- webextension/scripts/about.js
Links are dynamically generated from the list in code so it'll stay in sync in the future.
> Links to TV news sources in About page

- webextension/scripts/utils.js
Right-click menu tweak:
- move SPN to top
- add separator
- prevent show on toolbar
> Tweak right-click context menu

- appstores/changelog.md
- appstores/description.md
- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
Updated changelog and version to v3.1 (before bug fix)
> v3.1 pre-release

- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
- webextension/scripts/login.js
- webextension/scripts/popup.js
> Check the username when the login get succeed

- webextension/scripts/background.js
Enhancement in response to #940
> Hide count badge during SPN to make hour-glass more visible

- appstores/changelog.md
- appstores/chrome/README.md
- appstores/description.md
- appstores/edge/README.md
- appstores/firefox/README.md
- appstores/safari/README.md
- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
- updated release notes for app stores
> v3.2 Release

- .github/workflows/continuousIntegration.yml
- package-lock.json
- package.json
- test/setup.js
- webextension/css/bootstrap.css
1. Updated the package that needs updating
2. Move `bootstrap` and `fontawesome-free` from devDependencies to dependencies since they are used at runtime.
3. Move `url-loader` from dependencies to devDependencies.
4. Fix an warning issue for `bootstrap.css.map System error: net::ERR_FILE_NOT_FOUND `
> Update dependancies and package.json file

- appstores/changelog.md
- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
This updates the version numbers in the manifest and Xcode files, and updates the changelog.
> v3.3 Release

- appstores/changelog.md
- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/manifest.json
This version includes
1. Inform patron if cookies are turned off when logging in
2. Added more url patterns in exclude list for auto-save
> V3.3.1 Release

- TESTING_GUIDE.md
> Updating testing guide doc

- webextension/scripts/utils.js
> Update `feedbackURLs` for Chrome and Chromium

- webextension/scripts/utils.js
Added 2 more links to PR #1027 for Issue #1012
> Added updated feedbackURLs for Brave and Opera

- safari/Wayback Machine.xcodeproj/project.pbxproj
- webextension/index.html
- webextension/manifest.json
- webextension/scripts/background.js
- webextension/scripts/popup.js
- webextension/scripts/settings.js
- webextension/scripts/utils.js
UI improvements to handle slow archiving process that might happens sometimes.
> UI improvements to handle slow archiving
