index.html, scripts/buttonlisteners.js, scripts/functions.js
this pr aims to resolve #3 issue , it directly calls respective funtions from button listeners and avoids going through the if else block in function.js as this if else block fails sometimes like when recent/first version buttons are clicked after clicking save button(which opens new tab) , then one more tab for save button opens up because save_now variable remains equal to 1 .
=> removed if else block from function.js

manifest.json
Event pages are loaded only when they are needed. It increases the performance especially on low-powered devices.
=> Added Event Pages

manifest.json, scripts/background.js
This pull request adds integration with the Wayback Machine's Site Search through the omnibox (**showing suggestions**), simply by typing "wm [TAB or space] [search query]".
Here you can see this feature in operation by looking for "google".
Any feedback is more than welcome!
=> Integration with the Wayback Machine's Site Search (through the omnibox, showing suggestions)

scripts/background.js
Currently "Wayback Machine" context menu appears on all pages, including Chrome Extensions page (chrome://extensions) and browser action popup.
While context menu on browser action popup works OK, it looks out-of-place. It is not useful at all to show context menus items like "First Version" on Chrome Extensions page.
This patch adds `documentUrlPatterns` option to each of menu items, to show them on http, https and ftp URLs only. Browser action button context menu still has all extension menu items, even when active tab is Chrome Extensions page.
Menu item description is getting a bit verbose -- I leave it for another edit to clean them up.
=> Don’t show extension context menu where it is not archivable

scripts/RTcontent.js
Named charachter reference terminated by semi-colon
file : RTcontent.js
line no 30.
fixes: #97
=> charachter reference terminated by semi-colon

manifest.json, scripts/background.js
The try catch block was not working because the error was not being thrown. The error is stored in `chrome.runtime.lastError`. I checked for this inside the callback for `chrome.tabs.executeScript()` and if it is set to `Cannot access contents of url "chrome-error://chromewebdata/` then I displayed dnserror.html.
=> Fixed 503 interception

css/doi.css, css/singleWindow.css, doi.html, manifest.json, scripts/background.js, scripts/doi.js, scripts/settings.js, scripts/singleWindow.js, settings.html, singleWindow.html
All DOI's from a Wikipedia page are displayed as a context with links to read at web.archive.org
DOI's are read from the page, queried at https://scholar.archivelab.org/id/doi/ and sent to background.js as an array. Then the context screen requests this array from background.js and displays the DOI's and links on doi.html or singleWindow.html
=> DOI links feature

scripts/singleWindow.js, scripts/tagcloud.js
Use `https://archive.org/services/context/papers?url=example.com` instead of
`http://web.archive.org/__wb/search/tagcloud?n=example.com&counters=1`.
Remove multiple redundant `console.log` commands.
=> Replace tagcloud context URL

scripts/overview.js, scripts/singleWindow.js
Use `https://archive.org/services/context/metadata?url=example.com`
Instead of `http://web.archive.org/__wb/search/metadata?q=example.com`
=> Replace metadata context URL

manifest.json, package.json, scripts/doi.js
Updated `https://archive.org/services/context/papers?url=<URL>` has a
new metadata format with minor changes.
We update the extension code reading JSON from /papers to use the new
format.
The paper UI remains exactly the same.
Bump version to 3.1.0.
=> Update papers UI to handle new /papers context format

booklist.html, scripts/booklist.js
Fix a bug with spinning loader that keeps working even though we haven't
found any books.
Replace `XMLHttpRequest` code with `$.getJSON` to simplify code.
Fix eslint errors.
=> Fix spinning loader in books context

booklist.html, css/wikipedia.css, manifest.json, scripts/booklist.js, scripts/wikipedia.js, scripts/wikipedia_loader.js, test/wikipedia.spec.js
I made a content script that runs on wikipedia pages to display a button to read the book next to citations.
I made the changes suggested in the previous PR, which included using a function `get_ia_books(url)` in both this content script and the booklist.js script.  In a commit from over the weekend, this was also changed in the booklist.js script to use `$.getJSON()`.  In dealing with the merge conflict, I opted to use the `get_ia_books(url)` function, however, we can modify the function to use `$.getJSON()` if we prefer that to using `fetch`.  
Also, I really don't like how the buttons look right now.  Mark said to make them green, small, and have an archive icon to the left of the text, which should say "Read."  I think it would look better if it were either the archive logo with …
=> Wikipedia content script

annotation.html, css/annotation.css, package.json, scripts/annotation.js, scripts/annotation_loader.js
Rewrite `annotation.js` using jQuery.
Cleanup annotation.html markup and CSS rules.
The UI remains exactly the same as before.
=> Optimise annotation context code

scripts/background.js, scripts/dnserror.js
When a page is not found (e.g. 404), we are redirected to a "Not Found"
page.
That page had invalid URL parameter separators (`?` everywhere instead
of `&` !!) like this:
```
chrome-extension://leihjocjpbflfcepbmiappahbckagncn/dnserror.html?wayback_url=https://web.archive.org/web/20180821103430/http://dataopen.eu/?page_url=http://dataopen.eu/?status_code=404?
```
We fix this bug and improve the code to get the parameter values in
`scripts/dnserror.js`.
=> Fix invalid not found handler URL parameters format

annotationURL.html
I have fixed the bug, when I try for finding Annotations of Current URL for an URL, I am not seeing the user name which I could see in Annotations of Current Domain.
I have replaced the ID by Class for which it was not working.
Thank you!!
=> Fixed bug regarding not seeing user name in annotation_URL context

scripts/background.js
Remove redundant showall option handling in scripts/background.js
Fix horrible code indentation.
Move functions outside callback to simplify code structure.
Move context menu code outside chrome.webRequest.onCompleted.addListener
Remove redundant console.log commands.
Reduce script lines of code to ~1000.
=> Background code reorganization

scripts/background.js
The following bug has been fixed:-
When I select option "Show context in tabs", I pick Alexa & domaintools contexts, I enable auto-update-context.
When I visit one site, contexts appear correctly. When I visit another site, contexts refresh but instead of Alexa as the first context, I see the papers context
=> Fixed bug regading alexa and doi conflict in context auto-update

scripts/background.js
The method we have to check if we are in an amazon.com book URL in order
to lookup `archive.org/services/context/amazonbooks` did not work
correctly because it checked the previous format of the results and not
the new one.
We fix this bug.
=> Suggestion to read amazon.com books doesn't show up

index.html, manifest.json, scripts/background.js, scripts/popup.js, scripts/utils.js
`scripts/background.js` had a function to check WBM availability `wmAvailabilityCheck()`.
`scripts/popup.js` had another function which did the SAME thing but also called SPN
in the file wasn't archived. `check_url()`.
We do the following:
Move WBM availability checking functions to `scripts/utils.js` and
modify `manifest.json` to load `scripts/utils.js` before
`background.js`.
Delete duplicate functions from `scripts/popup.js` and make it use
WBM availability checking functions from `scripts/utils.js`.
Perform additional code cleanups in `scripts/popup.js`.
=> Remove duplicate WBM availability check functions

doi.html, scripts/doi.js, test/doi.spec.js
- Includes utils.js in doi.html and eliminates `getUrlByParameter()`
- Breaks large function into smaller units and adds some tests
=> Refactors wikipedia papers CS

scripts/background.js
Merge individual `chrome.storage.sync.get` methods for `show_context`, `auto_update_context` and `books` settings to make less calls and have less code.
Use `fetch()` instead of `XMLHttpRequest` to make the amazon books back-end request.
Remove redundant intermediate vars.
=> Refactor background.js

scripts/background.js
While fixing this bug, I noticed that if the Context Window(s) are closed before they finish loading, the background.js console blows up with errors.  I'm continuing to investigate.
=> Fixes bug where new tabs are made in current window instead of new window

scripts/wikipedia.js
archive.org/services/context/books may need more than 10'' when there are
many books available. Its very fast as it runs background lookups in
parallel (6 threads) but still it may need more than 10''.
=> Increase /books timeout limit from 10 to 30 sec

manifest.json, scripts/background.js, scripts/popup.js
I can add a setting where the user can paste their access and secret keys so they won't have to sign in, but after testing it as is, it's not hard to just sign in to use SPN2 as it will prompt the user right away.
=> Replaces Save Page Now with SPN2 (web-beta)

css/welcome.css, manifest.json, scripts/background.js, scripts/settings.js, scripts/welcome.js, settings.html, welcome.html
Mark wanted a similar ToS agreement to the [Alexa Internet Extension](https://chrome.google.com/webstore/detail/alexa-traffic-rank/cknebhggccemgcnbidipinkifmmegdel?hl=en).  
It's functioning properly if on a fresh install, when you click the extension icon, it opens a new tab with a ToS agreement.  If you click agree, it sets the default popup back to index.html. Else, it just closes the window and doesn't change the browserAction behavior.  
The things I'd like to get feedback on:
- Any bugs?
- Style/Content of the ToS page
- Should I give any UI feedback for clicking agree or cancel? 
- Right now, either option just closes the window.
- The Alexa Internet extension redirects to a "success" page on agree.
=> Adds a terms of service agreement on fresh installs of the extension

scripts/background.js
The function isNotExcludedUrl returns true if the URL is not excluded, false if it is excluded. In function **auto_save** , !isNotExcludedUrl is being used, when it is to be just isNotExcludedUrl.
This was causing a bug wherein BadgeText "S" was not being added to the icon, when the page had not been archived.
=> Fixed improper usage of "isNotExcludedUrl" 

scripts/background.js, scripts/popup.js
@MaxReinisch @anishsarangi 
**Explanation of the previous bug:** 
Since Chrome browser will cache your page, once we switch back to the tabs which we have already requested, chrome will not update the tab hence ```fetch``` will not execute. In this situation, the url stored in the chrome storage will not be updated as well so we will see that the extension is fetching the previous book.
Sorry about the fact that I am still using chrome storage to implement it this time because it is the easiest way to get shared data across all extension files in my opinion. Besides, I will only store two key-value pairs so memory throttling might not be a problem here.  
**Current solution:** 
For each request from ```background.js```, I store two key-value pairs, which are the tab url and the fetched …
=> Fixing Issue/314: amazon books now will only make one request

.eslintrc, css/index.css, index.html, scripts/booklist.js, scripts/citations.js, scripts/popup.js, settings.html
Now the user can select the context options from the extension itself. No need to open settings page every time to change options. This leads to better and easy use of the feature by a user. They can easily add or remove context options when they want to see them. 
Issue: #348
=> Context options refurbish

scripts/popup.js, scripts/settings.js, scripts/utils.js
Previously, in `popup.js`, we are using a variable called `global_url` to store the current tab URL, however, the way we acquire the URL is by calling the `chrome.tabs.query` method, which is an asynchronous function. Hence we might fail to acquire the tab URL sometimes.
Now every time we need the tab URL, we just simply calling this method and do the following operations asynchronously.
=> Refactoring global_url related code

scripts/popup.js
1. Changed Twitter share URL in popup.js Fixes #436 
2. Use of isNotExcludedUrl rather than manual checking
=> Twitter share url change and use of general method

scripts/welcome.js
There was a bug in firefox, while the user is accepting "Internet Archive Terms of Use and Privacy Policy" or cancelling, the tab was not closing. In this PR, I have fixed that bug
=> Fix bug in welcome page not closing in firefox

context.html, scripts/alexa.js
This PR includes fix to a bug in alexa context screen. Now Show Related data will show when data is there.
=> Show related sites when data is there in Alexa Context Screen

scripts/utils.js, test/utils.spec.js
Please test on Firefox on a variety of websites.
Try to see if you can test against multiples of 10, such as: 100, 1K, 10K, 100K, 1M.
The goal is for the text to be fully visible, without any of it cut off.
=> Shortened Count Badge to work on Firefox

css/context.css, scripts/annotation.js
This PR improves the content representation of the Annotations Context Page.
1. The text layout is distorted due to `word-break: break-all;`
The words are being broken at the right border of the box due to this property.
2. The "There are no annotations for the current URL." is at center now after removing some CSS classes.
Removing `word-break` and some classes provide a fix.
=> Improve the content representation in Annotations Screen

scripts/background.js
In this PR I have removed the array of HTTP_CODE and used `details.statusCode >= 400` instead of looking up in the array. By doing this it also reduces the time complexity to constant time.
Fixes #519
=> Remove array where it contains a list of HTTP_CODE

css/archive.css, scripts/background.js
This PR fixes the following issues
1. This feature works even without clicking on the "Accept and Enable" button in the Welcome 
page. This should not happen
2. We can add `cursor: pointer` in #close { } in archive.css.
In developer edition of firefox I am testing this, I got to know why it is happening, but still thinking of a solution.
=> fixed error-404-popup bug

scripts/background.js
This PR solves the issues in displaying Related TV Clips. 
1. There was a URL mismatch in `background.js`: https://apnews.com isn't the same as https://www.apnews.com since we are matching strings.
=> URL mismatch 

scripts/utils.js
As suggested by Mark, this hides the address bar for Show Context in a new window. Doesn't (can't) hide if opened in a new tab.
=> Hides URL address bar for contexts shown in a new window

scripts/background.js, scripts/popup.js
This PR ensures the following:
1. "Saving Snapshot..." and "Save Successful" messages can only be seen on the tab which is being/has been saved.
2. The toolbar icons ('S' and 'check') can only be seen on the tab which is being/has been saved.
Issue #530
=> Fix Saving Messages

scripts/context.js
This PR provides the following fixes:
1. Open the first tab if the user is accessing the Context Page for the first time.
2. Open the previously opened tab when the user switches between webpages with **"Auto-update Contexts"** option enabled.
3. Open the first tab if the previously opened tab is not selected in the Contexts menu.
4. Open the previously opened tab if it's option is selected in the Contexts menu.
=> Set Tabs to be Opened in Context Page

scripts/popup.js, scripts/settings.js
This PR provides the following fixes:
1. Clicking 'Enable in Settings' opens Context settings.
2. Dimming the 'Show Contexts' button when disabled.
=> Fix 'Show Contexts' button bugs

context.html, css/context.css, scripts/context.js
This PR shows an error message to the user on the 'Context' page if there are no contexts selected.
=> Show error message on empty Context screen

scripts/background.js, scripts/popup.js
This fixes #551 so that Saving ('S') works on pages which are also Relevant Archived Resources ('R'). Once SPN finishes, normally it would show a check icon, but if it's also an 'R' page, it will go back to showing 'R' again. The blue buttons will also show correctly now during SPN.
I changed the data structure of the toolbar state so that instead of assigning a string such as 'R' 'S' or 'check' per tab, I assign a Set() of strings instead, to support multiple states per tab simultaneously.
=> Toolbar icons now work with multiple concurrent states.

about.html, scripts/about.js, scripts/popup.js, scripts/utils.js
This PR provides the following fix:
The **Feedback** button in the extension and the **Write a Review** option in the **About** page now open the appropriate feedback pages depending on the browser (Chrome/Firefox).
=> Open Feedback URL Depending on Browser

webextension/scripts/popup.js
This PR disables the Extension Search Bar for Excluded URLs.
=> Search-box disabled for Excluded URLs

test/utils.spec.js, webextension/scripts/background.js, webextension/scripts/popup.js, webextension/scripts/utils.js
- Fetching the WB Count / Badge Count
- SPN (in the Popup as well as in the right click menu)
- Oldest/Overview/Newest (in the Popup as well as in the right click menu)
- Site Map
- Related Tweets
- Show Contexts
- Social Share
- Search Box
=> Clean URL when on 'web.archive.org'

webextension/css/index.css, webextension/index.html, webextension/scripts/popup.js, webextension/scripts/settings.js, webextension/scripts/utils.js
- Also Hide the WB Count and Archived Resources (`'R'` icon and blue buttons), if these exist.
=> Use search box value for extension features

webextension/scripts/overview.js
I have removed two duplicate function  `timestamp2datetime` and `_splitTimestamp` in overview.js.
It is replaced by `timestampToDate` in utils.js
=> Remove duplicate function in overview.js

webextension/css/doi.css, webextension/css/index.css, webextension/index.html, webextension/scripts/background.js, webextension/scripts/doi.js, webextension/scripts/popup.js
1. Fixes [this](https://github.com/internetarchive/wayback-machine-chrome/pull/619#pullrequestreview-451174366), enabling the user to go further down the search-box list.
2. Hides "Using Search URL" text when not using search box url.
=> Exclude UP & DOWN keys from event

webextension/context.html, webextension/manifest.json, webextension/scripts/alexa.js, webextension/scripts/annotation.js, webextension/scripts/background.js, webextension/scripts/context.js, webextension/scripts/domaintools.js, webextension/scripts/overview.js, webextension/scripts/tagcloud_loader.js
This PR fixes the bugs on Context pages:
=> Fix Context screen bugs

webextension/css/index.css
This PR removes the max-height of the popup.
This is needed for firefox as we would not like to have scrollbars in our extension
=> Remove max-height of popup

webextension/css/context.css, webextension/scripts/overview.js, webextension/scripts/tagcloud.js
This PR hides the wordcloud and thumbnail containers initially, and shows them when the data is fetched from the API.
=> Context Screen bugs

webextension/scripts/background.js, webextension/scripts/resource_list.js
BUG :
For some URLs, "Resource List" feature doesn't works as expected.
To replicate, make sure you have selected the 'Show Resources During Save' option in 'General' settings.
Example 1: Visit  http://brainsters.in/  and Save the page.
Example 2: Visit  https://web.archive.org/  and Save the Page.
Above bug is fixed in this PR !
=> Resource-list showing bug fixed

webextension/scripts/utils.js
This PR adds 'edition.cnn.com' to `newshosts` which enables the detection of TV News Clips for this website.
=> Add 'edition.cnn.com' to newshosts

webextension/scripts/background.js, webextension/scripts/bulk-save.js, webextension/scripts/popup.js
- Fixes #696 timeout issues by removing the Availability API call from Bulk Save and adds an option to SPN instead.
- savePageNow() options converted from array to an object internally.
- Handles a new case when *Save Page Now* clicked, will notify the user if it can't save due to another recent save.
=> Fixes Availability timeout issue in Bulk Save, notify for recent saves

webextension/scripts/background.js, webextension/scripts/context.js, webextension/scripts/popup.js, webextension/scripts/utils.js, webextension/scripts/wikipedia_loader.js
Adding checks for undefined, mostly from reading from local storage.
Renamed variable to 'settings'.
Should prevent errors from showing up such as in #704
=> Add null checks to prevent errors

webextension/scripts/popup.js, webextension/scripts/utils.js
After loading (or reloading) the extension for the first time, after agreement, the popup will display a tooltip over the Settings tab icon in order to direct the user's attention to Settings. After hovering over the Settings tab icon, the tooltip will be turned off on all future popups.
=> Settings tab tooltip to display on first popup

test/utils.spec.js, webextension/scripts/bulk-save.js, webextension/scripts/utils.js
Bug fix for undefined or null URL passed to cropPrefix()
```
Error in event handler: TypeError: Cannot read property 'slice' of undefined
scripts/utils.js:235 (cropPrefix)
scripts/bulk-save.js:232 (processStatus)
scripts/bulk-save.js:169 (anonymous function)
// Returns substring of URL after :// not including "www." if present.
// Also crops trailing slash.
function cropPrefix(url) {
if (url.slice(-1) === '/') { url = url.slice(0, -1) }
let re = /^(?:[a-z]+\:\/\/)?(?:www\.)?(.*)$/
let match = re.exec(url)
return match[1]
}
```
=> Fixed null bug in cropPrefix()

webextension/dnserror.html
This fixes the following Firefox console error when **dnserror.html** is loaded when a domain doesn't exist.
> The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
=> added missing utf8 encoding declaration

webextension/index.html, webextension/scripts/popup.js
Searching Tweets was stripping out the http(s) on the URL. This adds it back and properly encodes the URL.
=> Fix to Search Tweets

webextension/scripts/archive.js, webextension/scripts/background.js, webextension/scripts/bulk-save.js, webextension/scripts/doi.js, webextension/scripts/fact-check.js, webextension/scripts/popup.js, webextension/scripts/recommendations.js, webextension/scripts/settings.js, webextension/scripts/utils.js, webextension/scripts/wikipedia.js
Some fixes to issue #740 Firefox Compatibility.
Adds dummy checks to chrome.runtime.lastError to suppress console errors.
This error in console `Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved` is not fixed due to an unresolved bug in Firefox which I can't fix. It's reported to occur in other extensions here: https://bugzilla.mozilla.org/show_bug.cgi?id=1665380
The `This page uses the non standard property “zoom”` console error is from Bootstrap using `zoom` in CSS. Hopefully updating that will fix it.
=> Firefox Compatibility Fixes

webextension/bulk-save.html, webextension/css/bulk-save.css, webextension/scripts/background.js, webextension/scripts/bulk-save.js, webextension/scripts/popup.js
Makes a number of improvements to Bulk Save, including Pause and Continue, which will reset pending items and add them back to the queue for saving. Adds buttons so that the user can copy saved items' Wayback Machine links, or links of unsaved items to try again later.
#731 #741 #743 #754
=> Implement Pause & Continue, Copy Links buttons to Bulk Save

webextension/css/index.css, webextension/manifest.json, webextension/scripts/archive.js, webextension/scripts/background.js, webextension/scripts/bulk-save.js, webextension/scripts/dnserror.js, webextension/scripts/popup.js, webextension/scripts/resource_list.js, webextension/scripts/utils.js
Strangely, there's some glitching and slowdowns while hovering over popup buttons in Chrome now, where before this only occurred in Safari. Likely due to the massive `style.css` file which I'll work on next.
There's a bug in Safari regarding `manifest.js`: Under `"content_scripts"` the `"matches"` field appears to be ignored by Safari and js and css files in this section are inserted in ALL websites instead of just Wikipedia. Seems to only occur when "Always Allow on Every Website..." button is selected in preferences (which is recommended) but this causes all sorts of problems on websites...
=> Variety of Safari bug fixes

webextension/scripts/background.js
=> Remove checking the current active tab-url and tabId in amazon book feature

package.json, safari/Wayback Machine.xcodeproj/project.pbxproj, test/utils.spec.js, webextension/manifest.json, webextension/scripts/background.js, webextension/scripts/bulk-save.js, webextension/scripts/popup.js, webextension/scripts/utils.js
The involved redefining get_clean_url() to return URLs extracted from Extension pages in addition to web.archive.org pages. Renamed this function to getCleanUrl().
Changed the 'openurl' message in background.js and moved Save Page Now to it's own 'saveurl' message.
=> Popup buttons work while viewing Extension pages

package.json, safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/bulk-save.html, webextension/css/bulk-save.css, webextension/manifest.json, webextension/scripts/bulk-save.js
Limits number of URLs that may be added to list of URLs in Bulk Save. Includes code for fetching this max value from a remote API. (currently disabled as API endpoint still needs to be determined.)
If this value < 0, then remove any limit. If == 0, then inform user that Bulk Save is unavailable.
=> Bulk Save Limits feature

webextension/scripts/background.js
If someone reload the extension OR install it new, by default the “404 option is checked” in the settings. Then if user is selecting some more options and then if the user is selecting and deselecting private mode, you can see that all other checkboxes are checked. It is not restoring to its previous state.
This PR is a fix to that
=> Add 404 setting options to private_before_default and remove others

webextension/manifest.json
Everything seems to work fine with 'tabs' permission removed from manifest, since the 'activeTab' permission allows use of tabs. Could use further testing in all 3 browsers.
=> Removed 'tabs' permission from manifest

package.json, safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/css/settings.css, webextension/index.html, webextension/manifest.json, webextension/scripts/background.js, webextension/scripts/settings.js, webextension/scripts/utils.js
Implements #673 
This enhances the Auto Save Page feature by adding a dropdown list to Settings. Now instead of only auto-saving if a website has never been archived before, the user can specify an age such as 1 year, 90 days, or as soon as 24 hours. This would activate Auto Save if the latest archive is at least that age or older.
Known Issue: Setting Private Mode may not correctly clear Auto Save. This will be fixed in a future PR.
=> Auto Save Age dropdown in Settings

package.json, safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/manifest.json, webextension/scripts/utils.js
Noticing an issue under Firefox and multiple monitors, popup windows wouldn't size correctly. They'd show up on the 2nd screen, size too large for the screen, which Firefox would then resize to a really small window. This PR fixes that issue and defines a max width.
=> Tweak size of popup windows

package.json, safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/manifest.json, webextension/scripts/background.js, webextension/scripts/utils.js
fixes #821 
There was a delay in updating the Archiving state, including toolbar icon, after Save Page Now completed successfully. It was noticeable when the Save Resource List window was open. The delay was so long on Safari that it appeared SPN was stuck at times. It also affected Auto-Save. This PR fixes this issue after rewriting the SPN status function.
=> Remove delay from SPN to quicken success status

webextension/scripts/tvnews.js
For now we are removing the threshold value condition in tvnews.js. We will add this filtering in the `/tvnews` backend.
=> Remove threshold value comparision in tvnews.js

safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/manifest.json, webextension/scripts/background.js, webextension/scripts/popup.js, webextension/scripts/spn-redirect.js, webextension/spn-redirect.html
improving #891
Opens a Wayback Machine webpage to Save Page Now anonymously when SPN button pressed.
Since there's no direct way to POST to a URL inside web extension code, I had to open a temporary internal page to automatically submit a form while passing in the URL to save.
=> Save Without Login using a form redirect

webextension/scripts/utils.js
Reset my archive settings after reloading the extension to false by default.
=> Reset my archive settings after reloading the extension

webextension/css/welcome.css, webextension/welcome.html
We noticed that some users missed the Accept button in the Welcome screen, which would show repeatedly since they never clicked on the Accept button before closing the window. This PR places the buttons fixed along the bottom edge so that they're always visible.
=> Welcome page buttons always visible

safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/index.html, webextension/manifest.json, webextension/scripts/popup.js
Fixes a bug where settings such as "Outlinks" or "Save To My Web Archive", if set while logged in, remain set when logged out.
=> Clear settings that should be clear when logged out

safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/css/settings.css, webextension/index.html, webextension/manifest.json, webextension/scripts/popup.js, webextension/scripts/settings.js, webextension/scripts/utils.js
Implements #896
Adds 'Same Tab' option to Settings:
There's a reported bug in Chrome where the browser's Back button won't let the user go back to the prior page after opening a URL when Same Tab option is active. Works fine in Firefox.
=> Show features in Same Tab option

TESTING_GUIDE.md, safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/index.html, webextension/manifest.json, webextension/scripts/background.js, webextension/scripts/popup.js, webextension/scripts/utils.js
There are over 1K+ websites currently excluded from view on the Wayback Machine.
While Save Page Now on these URLs will still work, one cannot view its archive.
This will:
- Disable the relevant buttons.
- Display a message to inform the user.
- Prevent Auto-Saves from running on excluded pages.
- Fixes #944
Can test against this website:
https://www.tomshardware.com/
Status text `URL has been excluded` changed to `URL excluded from viewing`
=> Manage websites excluded from viewing on the Wayback Machine

safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/css/settings.css, webextension/index.html, webextension/manifest.json, webextension/scripts/settings.js
This is a Settings UI change to move the "Errors Pop-Up in Page" Setting in the first panel, to inside the 404 Setting in the second panel. When the 404 setting isn't active, the pop-up setting is disabled.
| Before | After |
| --- | --- |
=> Move pop-up setting to within 404 setting

safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/index.html, webextension/manifest.json, webextension/scripts/background.js, webextension/scripts/settings.js, webextension/scripts/utils.js
Implements #902 
Adds "Disable Notifications" to Settings which will turn off any notifications from displaying in Chrome, Firefox, and Edge. This Setting will be hidden on Safari, since Safari already never displays notifications. If this changes in the future, the Setting will then display depending on if the browser supports it.
This PR also refactors and cleans up unused code related to alerts and notifications.
=> Option to Disable Notifications

TESTING_GUIDE.md
Remove an url that longer redirects to 404 from testing guide
=> Remove an url that longer redirects to 404 from testing guide

safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/manifest.json, webextension/scripts/login.js, webextension/scripts/utils.js
implements #911
This fixes a common complaint when the user cleared their cookies and found themselves logged out. This PR will keep them logged in until they explicitly log out using the log out button in the extension. This works by storing a copy of the auth cookies in storage and restoring them after cookies were cleared and the user clicks the toolbar button.
=> Stay logged in after user clears cookies

safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/manifest.json, webextension/scripts/background.js, webextension/scripts/settings.js
Fixes #964
- Replaces Availability API call with cached WM count (sparkline) API call in autoSave().
- Tested on Chrome. Needs testing still on Firefox, Edge, Safari.
=> Prevent Auto Save from re-saving recently saved pages

safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/index.html, webextension/manifest.json, webextension/scripts/background.js, webextension/scripts/settings.js
Implements #749 
- Auto Saves when user bookmarks a web page, without notification.
- Ignores excluded URLs including user-defined Exclude URLs.
- Uses optional 'bookmarks' permission to avoid warnings at install time, which means the browser will ask permission when user tries to check the setting for the first time.
- Can't save multiple tabs at once. Will only save the current tab.
- Doesn't attempt to save when importing a list of bookmarks.
- Hides the setting in Safari, since bookmark access not supported.
- Tested on Chrome, Firefox, Edge, and Safari.
=> Auto Save New Bookmarks

safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/manifest.json, webextension/scripts/background.js, webextension/scripts/utils.js
The right-click menu doesn't currently show when the Welcome Agreement page has not yet been accepted. This PR adds a "Welcome to the Wayback Machine" item to the right-click context menu, that when selected will open the Welcome Privacy Policy page, just like when clicking on the toolbar icon for the first time. This was added for those users who were used to using the right-click menu and may not realize one must first click on the toolbar icon and accept the agreement prior to using the right-click menu.
=> Welcome right-click context menu item

test/utils.spec.js, webextension/scripts/utils.js
Make changes in `isArchiveUrl` function to include mastodon.archive.org as a supported url in the extension.
=> Remove mastodon.archive.org from excluded urls

webextension/scripts/background.js
There is a change in the backend context service so that context_url is directly available in the api response.
Just need to check if the context_url key is available in the response and then show the yellow dot with button in the UI
=> Extract context_url directly from context api response

safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/manifest.json, webextension/scripts/login.js, webextension/scripts/utils.js
Performs some checks on whether extension can access cookies and informs the user when they login to _Please Enable Cookies_.
- Catches case when `privacy.firstparty.isolate` variable in Firefox is set true. See #983
- Catches when All Cookies are blocked in browser settings. (which usually also prevents websites from working correctly.)
=> Cookie settings check

safari/Wayback Machine.xcodeproj/project.pbxproj, webextension/manifest.json, webextension/scripts/exclude-list.js
This should fix #1019 by not closing the window until after saving the URLs in storage is finished.
v3.3.1.1
=> Fix for Excluded URLs not saving while Sync is on
